import Head from 'next/head'
import Header from '@/contexts/header'
import { useRouter } from 'next/router';
import Footer from '@/contexts/footer'

import styles from '@/styles/Home.module.css'
import { useForm } from 'react-hook-form';

export default function Home() {
  const { register, handleSubmit } = useForm()
  const router = useRouter()

  function handleEdit(data: any) {
    console.log({ Edited: data, Index: router.query })
  }

  return (
    <>
      <Head>
        <title>Influencial Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={styles.containerEditAddress}>
        <form onSubmit={handleSubmit(handleEdit)}>
          <div className={styles.editAddress}>
            <div>País/Região</div>
            <input {...register('country')} type="text" name="country" id="" />
            <div>Nome completo (nome e sobrenome)</div>
            <input {...register('name')} type="text" name="name" id="" />
            <div>Telefone</div>
            <input {...register('telephone')} type="text" name="telephone" id="" />
            <div>CEP</div>
            <input {...register('cep')} type="text" name="cep" id="" />
            <div>Endereço</div>
            <input {...register('address')} type="text" name="address" id="" />
            <div>Número da residência</div>
            <input {...register('number')} type="text" name="number" id="" />
            <div>Complemento (opcional)</div>
            <input {...register('complement')} type="text" name="complement" id="" />
            <div>Bairro</div>
            <input {...register('neighborhood')} type="text" name="neighborhood" id="" />
            <div>Cidade</div>
            <input {...register('city')} type="text" name="city" id="" />
            <div>Estado</div>
            <input {...register('state')} type="text" name="state" id="" />
            <div>Instruções de entrega (opcional)</div>
            <input {...register('instructions')} type="text" name="instructions" id="" />
            <div>
              <input type="checkbox" name="" id="" />
              <span>Tornar este o meu endereço padrão</span>
            </div>
          </div>
          <button>Salvar Informacoes</button>
        </form>
        
      </div>
      <Footer></Footer>
    </>
  )
}
