import Head from 'next/head'
import { useForm } from 'react-hook-form'

export default function Home() {
  const { register, handleSubmit } = useForm()

  async function handleRegister(data: any) {
    
    console.log(data)
  }

  return (
    <>
      <Head>
        <title>Influencial Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit(handleRegister)}>
        <div>Title do Item</div>
        <input
        {...register('Title')}
        ></input>

        <div>Url Imagem</div>
        <input
        {...register('Image')}
        ></input>

        <div>quantidade em estoque</div>
        <input
        {...register('productStock')} 
        ></input>

        <div>Preco no anuncio base</div>
        <input 
        {...register('Price')}
        ></input>

        <div>Categoria do Item</div>
        <input
        {...register('category')} 
        ></input>

        <div>Estara Ativo</div>
        <input
        {...register('active')} 
        ></input>
        
        <div>Url do Anuncio</div>
        <input
        {...register('urlProvider')} 
        ></input>

        <button type="submit">Register Item</button>
      </form>
    </>
  )
}
