import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useContext } from 'react'
import { AuthContext } from '@/contexts/AuthContexts'
import { parseCookies } from 'nookies'

export default function Home({ data, User }:any) {

  const { user, isAuthenticated } = useContext(AuthContext)

  return (
    <>
      <Head>
        <title>Influencial Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.logotype}></div>
        <div className={styles.navbar}>
          <input type="text" className={styles.bartext} placeholder={'Pesquisar Fornecedor, item etc...'}></input>
          <div className={styles.searchbar}>
            <svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path d="M39.8 41.95 26.65 28.8q-1.5 1.3-3.5 2.025-2 .725-4.25.725-5.4 0-9.15-3.75T6 18.75q0-5.3 3.75-9.05 3.75-3.75 9.1-3.75 5.3 0 9.025 3.75 3.725 3.75 3.725 9.05 0 2.15-.7 4.15-.7 2-2.1 3.75L42 39.75Zm-20.95-13.4q4.05 0 6.9-2.875Q28.6 22.8 28.6 18.75t-2.85-6.925Q22.9 8.95 18.85 8.95q-4.1 0-6.975 2.875T9 18.75q0 4.05 2.875 6.925t6.975 2.875Z"/></svg>
          </div>
        </div>
        <div className={styles.account}>
          <a href={"/login"}>
            <div className={styles.accountname}>Ola, <b>{ isAuthenticated ? (user?.name)?.split(' ')[0] : 'Login' }</b></div>
          </a>
          <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24"><path d="M12 15.05 6.35 9.375l1.05-1.05 4.6 4.6 4.6-4.6 1.05 1.05Z"/></svg>
        </div>
        <a href={"/shopping"}>
          <div className={styles.cart}>
            <svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path d="M14.35 44.25q-1.5 0-2.55-1.05-1.05-1.05-1.05-2.55 0-1.5 1.05-2.55 1.05-1.05 2.55-1.05 1.5 0 2.55 1.075 1.05 1.075 1.05 2.525 0 1.5-1.05 2.55-1.05 1.05-2.55 1.05Zm20 0q-1.5 0-2.55-1.05-1.05-1.05-1.05-2.55 0-1.5 1.05-2.55 1.05-1.05 2.55-1.05 1.5 0 2.55 1.075 1.05 1.075 1.05 2.525 0 1.5-1.05 2.55-1.05 1.05-2.55 1.05Zm-22.05-33 5 10.45h14.3l5.7-10.45Zm-1.85-3.6H39.1q1.5 0 2.3 1.35.8 1.35 0 2.75L35.15 23.1q-.6 1-1.525 1.625-.925.625-2.125.625H16.55l-2.6 4.9h24.3v3.6h-24.4q-2.35 0-3.35-1.575t.05-3.425l3.15-5.75L6.25 7.3h-4V3.7H8.6ZM17.3 21.7h14.3Z"/></svg>
            Carrinho
          </div>
        </a>
      </header>
      <div className={styles.banner}>
        <div className={styles.content}>
          <div className={[styles.keepShopping, styles.widgetVertical].join(" ")}>
            <div className={[styles.titleKeepShopping, styles.titleWidgetVertical].join(" ")}>CONTINUE COMPRANDO</div>
            <div className={[styles.itemsKeepShopping, styles.itemsWidgetVertical].join(" ")}>
              <ul>
                <li>
                  <a>
                    <img src='https://ae01.alicdn.com/kf/H1c37dff49df149999104a78c4d4d58e9O/Venda-quente-luz-t-nis-de-corrida-homem-t-nis-casuais-homens-moda-antiderrapante-sapatos-esportivos.jpg_Q90.jpg_.webp' ></img>
                  </a>
                </li>
                <li>
                  <a>
                    <img src='https://ae01.alicdn.com/kf/H1c37dff49df149999104a78c4d4d58e9O/Venda-quente-luz-t-nis-de-corrida-homem-t-nis-casuais-homens-moda-antiderrapante-sapatos-esportivos.jpg_Q90.jpg_.webp' ></img>
                  </a>
                </li>
                <li>
                  <a>
                    <img src='https://ae01.alicdn.com/kf/H1c37dff49df149999104a78c4d4d58e9O/Venda-quente-luz-t-nis-de-corrida-homem-t-nis-casuais-homens-moda-antiderrapante-sapatos-esportivos.jpg_Q90.jpg_.webp' ></img>
                  </a>
                </li>
                <li>
                  <a>
                    <img src='https://ae01.alicdn.com/kf/H1c37dff49df149999104a78c4d4d58e9O/Venda-quente-luz-t-nis-de-corrida-homem-t-nis-casuais-homens-moda-antiderrapante-sapatos-esportivos.jpg_Q90.jpg_.webp' ></img>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div className={styles.bannerNews}></div>
          <div className={styles.categories}>
            <div className={styles.titlecategories}>CATEGORIAS</div>
              {data.categories.map((categorie: any, index: any) => {
                return (
                  <a key={index} href={`categories/${categorie.code}`}>
                    <div className={styles.itemcategorie}>
                      <img src={categorie.img}></img>
                      <div className={styles.nameitem}>{categorie.name}</div>
                    </div>
                  </a>
                  )
              })}
          </div>
          <div className={[styles.recommended, styles.widget].join(" ")}>
            <div className={[styles.titleRecommended, styles.titleWidget].join(" ")}>RECOMENDADO PARA VOCE</div>
            <div className={[styles.itemsRecommended, styles.itemsWidget].join(" ")}>
              <ul>
                {data.recommended.map((recomended: any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${recomended.Code}`}>
                        <img src={recomended.Image} ></img>
                        <div> <strong>{recomended.Title}</strong> </div>
                        <div> {recomended.Evaluation }/5 - {recomended.CountEvaluation}</div>
                        <div> <strong>R$ {recomended.Price}</strong> </div>
                      </a>
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>
          <div className={[styles.bestSell, styles.widget].join(" ")}>
            <div className={[styles.titleBestSell, styles.titleWidget].join(" ")}>MELHORES VENDIDOS</div>
            <div className={[styles.itemsBestSell, styles.itemsWidget].join(" ")}>
              <ul>
                {data.bestSell.map((bestsell: any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${bestsell.Code}`}>
                        <img src={bestsell.Image} ></img>
                        <div> <strong>{bestsell.Title}</strong> </div>
                        <div> {bestsell.Evaluation }/5 - {bestsell.CountEvaluation}</div>
                        <div> <strong>R$ {bestsell.Price}</strong> </div>
                      </a>
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>
          <div className={[styles.discoveryDay, styles.widget].join(" ")}>
          <div className={[styles.titleDiscoveryDay, styles.titleWidget].join(" ")}>DESCOBERTAS DO DIA</div>
            <div className={[styles.itemsDiscoveryDay, styles.itemsWidget].join(" ")}>
              <ul>
                {data.recentProducts.map((recent : any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${recent.Code}`}>
                        <img src={recent.Image} ></img>
                        <div> <strong>{recent.Title}</strong> </div>
                        <div> {recent.Evaluation }/5 - {recent.CountEvaluation}</div>
                        <div> <strong>R$ {recent.Price}</strong> </div>
                      </a>
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>
          {
          User?.user?.itemsViewed.length > 0 ?
            <div className={[styles.historyView, styles.widget].join(" ")}>
              <div className={[styles.titleHistoryView, styles.titleWidget].join(" ")}>HISTORICO DE NAVEGACAO</div>
              <div className={[styles.itemsHistoryView, styles.itemsWidget].join(" ")}>
                <ul>
                {User.user.itemsViewed.map((itemViewed : any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${itemViewed.Code}`}>
                        <img src={itemViewed.Image} ></img>
                        <div> <strong>{itemViewed.Title}</strong> </div>
                        <div> {itemViewed.Evaluation }/5 - {itemViewed.CountEvaluation}</div>
                        <div> <strong>R$ {itemViewed.Price}</strong> </div>
                      </a>
                    </li>
                  )
                })}
                </ul>
              </div>
            </div>
          : ''
          }
        </div>
        <footer>
          dev knownetworks inc.
        </footer>
      </div>
    </>
  )
}

Home.getInitialProps = async (ctx: any) => {
  
  const listProducts = await fetch('http://localhost:3000/api/products/listproducts')
  const data: any = await listProducts.json()

  const categories = await fetch('http://localhost:3000/api/products/categories')
  data["categories"] = await categories.json()

  const { 'infshop.token': token } = parseCookies(ctx)

  
  if (token) {
    
    const User = await fetch('http://localhost:3000/api/auth/recovery/token',
    {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      method: "POST",
      body: JSON.stringify({ token: token })
    })
    const dataUser = await User.json()

    return {
      data,
      User: dataUser
    }
  } else {
    return {
      data,
      User: null
    }
  }
}
