import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/contexts/header'
import { parseCookies } from 'nookies'
import Footer from '@/contexts/footer'

export default function Home({ data, User }:any) {

  function passarItensDir(event: any) {
    const ul = event.currentTarget.parentElement.querySelector('ul')
    let value = parseInt(ul.dataset.transform) + 130

    if (value >= 0) value = 0

    ul.setAttribute('style',`transform: translateX(${ value }px)`)
    ul.setAttribute('data-transform', value)
  }

  function passarItensEsq(event: any) {
    const ul = event.currentTarget.parentElement.querySelector('ul')
    let value = parseInt(ul.dataset.transform) + (-130)

    if (value <= -1180) value = -1180

    ul.setAttribute('style',`transform: translateX(${ value }px)`)
    ul.setAttribute('data-transform', value)
  }

  return (
    <>
      <Head>
        <title>Influencial Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={styles.banner}>
        <div className={styles.content}>
          { User?.user?.itemsViewed.length > 0 ?
            <div className={[styles.keepShopping, styles.widgetVertical].join(" ")}>
            <div className={[styles.titleKeepShopping, styles.titleWidgetVertical].join(" ")}>CONTINUE COMPRANDO</div>
            <div className={[styles.itemsKeepShopping, styles.itemsWidgetVertical].join(" ")}>
              <ul>
                {User.user.itemsViewed.slice(0, 4).map((itemViewed : any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`categories/${itemViewed.Category}`}>
                        <img src={itemViewed.Image} ></img>
                        <h5>{itemViewed.Category}</h5>
                      </a>
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>
          :''
          }
          <div className={styles.bannerNews}></div>
          <div className={[styles.recommended, styles.widget].join(" ")}>
            <div className={[styles.titleRecommended, styles.titleWidget].join(" ")}>RECOMENDADO PARA VOCE</div>
            <div className={[styles.itemsRecommended, styles.itemsWidget].join(" ")}>
              <svg className={styles.esq} width="50" height="50" onClick={passarItensEsq}>
                <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
              </svg>
              <ul data-transform={0}>
                {data.recommended.map((recomended: any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${recomended.Code}`}>
                        <img src={recomended.Image} ></img>
                        <div> <strong>{recomended.Title}</strong> </div>
                        <div> {recomended.Evaluation }/5 - {recomended.CountEvaluation}</div>
                        <div> <strong>{(recomended.Price).toLocaleString('pt-br',{style: 'currency', currency: User.user.currency})}</strong> </div>
                        {recomended.Off && <div>{recomended.Off}% off</div>}
                      </a>
                    </li>
                  )
                })}
              </ul>
              <svg className={styles.dir} width="50" height="50" onClick={passarItensDir}>
                <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
              </svg>
            </div>
          </div>
          <div className={styles.categories}>
            <div className={styles.titlecategories}>CATEGORIAS</div>
              {data.categories.map((categorie: any, index: any) => {
                return (
                  <a key={index} href={`categories/${categorie.code}`}>
                    <div className={styles.itemcategorie}>
                      <img src={categorie.img}></img>
                      <div className={styles.nameitem}>{categorie.name}</div>
                    </div>
                  </a>
                  )
              })}
          </div>
          <div className={[styles.bestSell, styles.widget].join(" ")}>
            <div className={[styles.titleBestSell, styles.titleWidget].join(" ")}>MELHORES VENDIDOS</div>
            <div className={[styles.itemsBestSell, styles.itemsWidget].join(" ")}>
              <svg className={styles.esq} width="50" height="50" onClick={passarItensEsq}>
                <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
              </svg>
              <ul data-transform={0}>
                {data.bestSell.map((bestsell: any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${bestsell.Code}`}>
                        <img src={bestsell.Image} ></img>
                        <div> <strong>{bestsell.Title}</strong> </div>
                        <div> {bestsell.Evaluation }/5 - {bestsell.CountEvaluation}</div>
                        <div> <strong>{(bestsell.Price).toLocaleString('pt-br',{style: 'currency', currency: User.user.currency})}</strong> </div>
                        {bestsell.Off && <div>{bestsell.Off}% off</div>}
                      </a>
                    </li>
                  )
                })}
              </ul>
              <svg className={styles.dir} width="50" height="50" onClick={passarItensDir}>
                <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
              </svg>
            </div>
          </div>
          <div className={[styles.discoveryDay, styles.widget].join(" ")}>
          <div className={[styles.titleDiscoveryDay, styles.titleWidget].join(" ")}>DESCOBERTAS DO DIA</div>
            <div className={[styles.itemsDiscoveryDay, styles.itemsWidget].join(" ")}>
              <svg className={styles.esq} width="50" height="50" onClick={passarItensEsq}>
                <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
              </svg>
              <ul data-transform={0}>
                {data.recentProducts.map((recent : any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${recent.Code}`}>
                        <img src={recent.Image} ></img>
                        <div> <strong>{recent.Title}</strong> </div>
                        <div> {recent.Evaluation }/5 - {recent.CountEvaluation}</div>
                        <div> <strong>{(recent.Price).toLocaleString('pt-br',{style: 'currency', currency: User.user.currency})}</strong> </div>
                        {recent.Off && <div>{recent.Off}% off</div>}
                      </a>
                    </li>
                  )
                })}
              </ul>
              <svg className={styles.dir} width="50" height="50" onClick={passarItensDir}>
                <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
              </svg>
            </div>
            <div>Mostrar Mais</div>
          </div>
          {
          User?.user?.itemsViewed.length > 0 ?
            <div className={[styles.historyView, styles.widget].join(" ")}>
              <div className={[styles.titleHistoryView, styles.titleWidget].join(" ")}>HISTORICO DE NAVEGACAO</div>
              <div className={[styles.itemsHistoryView, styles.itemsWidget].join(" ")}>
                <svg className={styles.esq} width="50" height="50" onClick={passarItensEsq}>
                  <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                  <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
                </svg>
                <ul data-transform={0}>
                {User.user.itemsViewed.map((itemViewed : any, index: any) => {
                  return (
                    <li key={index}>
                      <a href={`provider/${itemViewed.Code}`}>
                        <img src={itemViewed.Image} ></img>
                        <div> <strong>{itemViewed.Title}</strong> </div>
                        <div> {itemViewed.Evaluation }/5 - {itemViewed.CountEvaluation}</div>
                        <div> <strong>{(itemViewed.Price).toLocaleString('pt-br',{style: 'currency', currency: User.user.currency})}</strong> </div>
                        {itemViewed.Off && <div>{itemViewed.Off}% off</div>}
                      </a>
                    </li>
                  )
                })}
                </ul>
                <svg className={styles.dir} width="50" height="50" onClick={passarItensDir}>
                  <rect x="10" y="10" width="30" height="30" rx="5" fill="#333" />
                  <path d="M20 25 L30 20 L30 30 Z" fill="#fff" />
                </svg>
              </div>
            </div>
          : ''
          }
        </div>
        <Footer></Footer>
      </div>
    </>
  )
}

Home.getInitialProps = async (ctx: any) => {
  
  const listProducts = await fetch(`http://localhost:3000/api/products/listproducts`)
  const data: any = await listProducts.json()

  const categories = await fetch(`http://localhost:3000/api/products/categories`)
  data["categories"] = await categories.json()

  const { 'infshop.token': token } = parseCookies(ctx)

  if (token) {
    
    const User = await fetch(`http://localhost:3000/api/auth/recovery/token`,
    {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      method: "POST",
      body: JSON.stringify({ token: token })
    })
    const dataUser = await User.json()

    return {
      data,
      User: dataUser
    }
  } else {
    return {
      data,
      User: null
    }
  }
}
