import Footer from '@/contexts/footer'
import Header from '@/contexts/header'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import { parseCookies } from 'nookies'
import { useEffect, useState } from 'react'

import PixSVG from '@/public/icon_pix.svg'
import CreditCardSVG from '@/public/credit-card.svg'
import BarCodeSVG from '@/public/bar-code.svg'

export default function Home({ productsInCart, token }: any) {
  const [productsCart, setProducts] = useState(productsInCart)
  const [method, setMethod] = useState("pix")

  useEffect(() => {
  }, [productsCart])

  useEffect(()=>{
    document.getElementById("nodePayment")?.childNodes.forEach((element:any)=>{
      element?.setAttribute('style','display: none;')
    })

    document.getElementById(method)?.setAttribute('style','display: block;')
  },[method])

  function changeMethod(event:any) {
    event.currentTarget.parentElement.childNodes.forEach((element:any) =>{
      element.setAttribute('style','background: #ffffff;')
    })
    event.target.setAttribute('style','background: red;')
    setMethod(event.target.value)
  }

  async function fireMethod(event:any) {
    await fetch('/api/products/method', {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      method: "POST",
      body: JSON.stringify({
        token: token,
        method: method
      })
    })

    window.location.href = '/checkout';
  }

  return (
    <>
      <Head>
        <title>Influencial Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={ styles.containerPayments }>
        <h2>Como deseja Pagar ?</h2>
        <div className={ styles.payment }>
          <div className={ styles.paymentMethods }>
            <button onClick={changeMethod} value="pix"><PixSVG width={24} height={24}></PixSVG>PIX</button>
            <button onClick={changeMethod} value="creditCard"><CreditCardSVG width={24} height={24}></CreditCardSVG>Cartao de Credito</button>
            <button onClick={changeMethod} value="bolbradesco"><BarCodeSVG width={24} height={24}></BarCodeSVG>Boleto</button>
          </div>
          <div className={ styles.paymentDescription } id="nodePayment">
            <div id="pix">
              <h2>PIX</h2>
              <br></br>
              <h4>A Melhor Opcao a vista para suas compras com desconto!!</h4>
              <br></br>
              <p>Pague com PIX e aproveite até <strong>20% OFF</strong>. Nessa modalidade, seu pedido é aprovado instantaneamente, o que torna a expedição do seu pedido ainda mais rápida.</p>
              <h2>Total da sua Compra</h2>
              <h3>R$ { (productsCart?.reduce((a: any,v: any) =>  a = a + v.Price , 0)).toFixed(2) }</h3>
              <h2>Pagamento Via Pix</h2>
              <h3>R$ { (((productsCart?.reduce((a: any,v: any) =>  a = a + v.Price , 0)))-((productsCart?.reduce((a: any,v: any) =>  a = a + v.Price , 0))*(8/100))).toFixed(2) }</h3>
              <h4>Economize: $ {(productsCart?.reduce((a: any,v: any) =>  a = a + v.Price , 0))*(8/100)}</h4>
              <div id="pixcode"></div>
            </div>
            <div id="bolbradesco">
              <h2>BOLETO</h2>
              <h2>Total da sua Compra</h2>
              <h3>R$ { (productsCart?.reduce((a: any,v: any) =>  a = a + v.Price , 0)).toFixed(2) }</h3>
              <div id="barcode"></div>
            </div>
          </div>
        </div>
        <button>Voltar</button>
        <button onClick={fireMethod}>Pagar com { method.charAt(0).toUpperCase() + method.slice(1) }</button>
      </div>
      <Footer></Footer>
    </>
  )
}

Home.getInitialProps = async (ctx: any) => {

  const { 'infshop.token': token } = parseCookies(ctx)
  
  if (token) {
    
    const User = await fetch(`http://localhost:3000/api/auth/recovery/token`,
    {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      method: "POST",
      body: JSON.stringify({ token: token })
    })
    const { user } = await User.json()

    return {
      productsInCart: user.productsInCart,
      token: token
    }
  } else {
    return {
      productsInCart: null,
      token: token
    }
  }
}
