import Footer from '@/contexts/footer'
import Header from '@/contexts/header'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import { parseCookies } from 'nookies'
import { useState } from 'react'

import PixSVG from '@/public/icon_pix.svg'
import CreditCardSVG from '@/public/credit-card.svg'
import BarCodeSVG from '@/public/bar-code.svg'

export default function Home({ productsInCart }: any) {
  const [method, setMethod] = useState(null)
  
  return (
    <>
      <Head>
        <title>Influencial Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={ styles.containerPayments }>
        <h2>Como deseja Pagar ?</h2>
        <div className={ styles.payment }>
          <div className={ styles.paymentMethods }>
            <button value="pix"><PixSVG width={24} height={24}></PixSVG>PIX</button>
            <button value="creditCard"><CreditCardSVG width={24} height={24}></CreditCardSVG>Cartao de Credito</button>
            <button value="barcode"><BarCodeSVG width={24} height={24}></BarCodeSVG>Boleto</button>
          </div>
          <div className={ styles.paymentDescription }>
            <h2>PIX</h2>
          </div>
        </div>
      </div>
      <Footer></Footer>
    </>
  )
}

Home.getInitialProps = async (ctx: any) => {

  const { 'infshop.token': token } = parseCookies(ctx)
  
  if (token) {
    
    const User = await fetch(`http://${ctx.req?.headers.host}/api/auth/recovery/token`,
    {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      method: "POST",
      body: JSON.stringify({ token: token })
    })
    const { user } = await User.json()

    return {
      productsInCart: user.productsInCart
    }
  } else {
    return {
      productsInCart: null
    }
  }
}
