import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { parseCookies } from 'nookies'
import { GetStaticPaths } from 'next'
import Header from '@/contexts/header'
import Footer from '@/contexts/footer'

export default function Home({ product }: any) {

  return (
    <>
      <Head>
        <title>Influencial Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={ styles.precart }>
        <div className={ styles.productInfo } >
          <img src={ product.Image }></img>
          <div>{ product.Title }</div>
        </div>
        <div className={ styles.buttonsInfo }>
          <h3>Produto Adicionado ao Carrinho</h3>
          <div className="break"></div>
          <a href="..">Continuar Comprando</a>
          <a href="../cart">Ir Para o Carrinho</a>
        </div>
      </div>
      <Footer></Footer>
    </>
  )
}

Home.getInitialProps = async (ctx: any) => {

  const { 'infshop.token': token } = parseCookies(ctx)
  const { product: productId } = ctx.query

  fetch('http://localhost:3000/api/products/cartproduct',
  {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      method: "POST",
      body: JSON.stringify({
        token,
        itemCode: productId
      })
  })

  const product = await fetch(`http://localhost:3000/api/products/${productId}`)

  if (product.status === 200) {
    return {
      product: await product.json()
    }
  }
}

const getStaticPaths: GetStaticPaths = async () => {
  

  return {
    paths: [],
    fallback: false
  }
}